name: ðŸ‘¥ Update Contributors

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  contributors:
    name: ðŸ‘¥ Update Contributors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: ðŸ‘¥ Generate Contributors
        uses: akhilmhdh/contributors-readme-action@v2.3.6
        with:
          filename: 'CONTRIBUTORS.md'
          use_username: true